ignore:
  - "examples"
  - "testdata"
  - "testutils"
  - "docs"
  - "**/*_test.go"
  - "**/*_mock.go"
  - "**/testdata/"
  - "**/testutils/"
  - "translation.ts"
coverage:
  status:
    project:
      default:
        flags:
          - client
          - server
fixes:
  - "src/::client/src/"