name: "CI Client"
on:
  push:
    branches:
      - main
      - add-client
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'client/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
      - run: make build-client
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
      - run: make lint-client

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
      - run: make test-client

  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
      - run: make coverage-client
      - run: ls -la
      - run: ls -la client
      - run: ls -la client/coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
          working-directory: client
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}